### PR TITLE
Prevent PHP error on missing get_plugin_data function

### PR DESCRIPTION
**Pull request by phpbits**
`get_plugin_data` seems to be missing and returning PHP error.

### CODE REVIEW

**Comment by tomjn** [comment]
I don't encounter this issue on my server, I hope you're not using Frontenberg in production 🤔

**Comment by phpbits** [comment]
@tomjn Same here but for some reasons I'm getting this issue on brand new installation. Probably an issue with the latest core version. I'm just using it on demo :)

**Comment by dovy** [comment]
Confirmed the same issue. It's visible when the newest version of the Gutenberg plugin is installed.

**Comment by tomjn** [comment]
I really don't like the idea of loading more of WP-Admin, I'd prefer to go in the opposite direction for security reasons. If it's a choice between fixing the function and jettisoning it, I'd prefer to jettison it.

I'm also not sure why it still works fine for me with the latest GB plugin on the live site

**Pull request closed without merging**
